"""add password

Revision ID: 51317f116b4c
Revises: 
Create Date: 2018-11-07 17:02:01.517665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51317f116b4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwrod', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_passwrod'), 'users', ['passwrod'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_passwrod'), table_name='users')
    op.drop_column('users', 'passwrod')
    # ### end Alembic commands ###
